#!/bin/bash
set -e

case "$1" in
    remove)
        # Keep /var/lib/beep-analytics on remove (user data)
        ;;
    purge)
        # Remove data on purge
        rm -rf /var/lib/beep-analytics
        ;;
esac
