#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        if systemctl is-active --quiet beep-analytics.service; then
            systemctl stop beep-analytics.service
        fi
        systemctl disable beep-analytics.service
        ;;
esac
